usr/share/doc/gnuradio*/README* /usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio*/html usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/CHANGELOG.md usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/config/thrift.conf.example usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/dial_tone.py usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/fm_demod.py usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/fm_rx.grc usr/share/doc/gnuradio-doc
usr/share/doc/gnuradio-3.8.3.1/fm_tx.grc usr/share/doc/gnuradio-doc
